export const MOVIES = [
"The Godfather"
,"Raiders of the Lost Ark"
,"Star Wars Episode V: Empire Strikes Back"
,"Shawshank Redemption"
,"Jaws"
,"GoodFellas"
,"Apocalypse Now"
,"Singin’ in the Rain"
,"Pulp Fiction"
,"Fight Club"
,"Raging Bull"
,"The Apartment"
,"Chinatown"
,"Once Upon a Time in the West"
,"The Dark Knight"
,"2001: A Space Odyssey"
,"Taxi Driver"
,"Casablanca"
,"The Godfather Part II"
,"Blade Runner"
,"The Third Man"
,"Star Wars Episode IV: A New Hope"
,"Back to the Future"
,"The Lord of the Rings: The Fellowship of the Ring"
,"The Good, the Bad and the Ugly"
,"Dr. Strangelove Or: How I Learned to Stop Worrying and Love the Bomb"
,"Some Like It Hot"
,"Citizen Kane"
,"Die Hard"
,"Aliens"
,"Gone with the Wind"
,"Butch Cassidy and the Sundance Kid"
,"Alien"
,"The Lord of the Rings: The Return of the King"
,"Terminator 2: Judgment Day"
,"Andrei Rublev"
,"A Clockwork Orange"
,"Heat"
,"The Matrix"
,"Vertigo"
,"The 400 Blows"
,"Kind Hearts and Coronets"
,"The Big Lebowski"
,"Schindler’s List"
,"Psycho"
,"On the Waterfront"
,"E.T. The Extra-Terrestrial"
,"This Is Spinal Tap"
,"Evil Dead"
,"Seven Samurai"
,"8 ½"
,"The Shining"
,"Donnie Darko"
,"The Lord of the Rings: Two Towers"
,"La Dolce Vita"
,"Casino Royale"
,"Lawrence of Arabia"
,"His Girl Friday"
,"Close Encounters of the Third Kind"
,"Come and See"
,"The Usual Suspects"
,"The Graduate"
,"Sunset Boulevard"
,"Oldboy"
,"Harold and Maude"
,"Edward Scissorhands"
,"Tokyo Story"
,"Annie Hall"
,"Three Colours Red"
,"Stand by Me"
,"The Night of the Hunter"
,"12 Angry Men"
,"Eternal Sunshine of the Spotless Mind"
,"The Treasure of Sierra Madre"
,"A Matter of Life and Death"
,"Manhattan"
,"Spartacus"
,"Rosemary’s Baby"
,"The Thin Red Line"
,"The Life and Death of Colonel Blimp"
,"Batman Begins"
,"The Great Escape"
,"Brazil"
,"L.A. Confidential"
,"Blue Velvet"
,"Carrie"
,"The King of Comedy"
,"Ferris Bueller’s Day off"
,"Magnolia"
,"When Harry Met Sally"
,"Star Wars Episode VI: Return of the Jedi"
,"Once Upon a Time in America"
,"Spirit of the Beehive"
,"The Wild Bunch"
,"Yojimbo"
,"American Beauty"
,"Reservoir Dogs"
,"North by Northwest"
,"Toy Story"
,"Network"
,"Raising Arizona"
,"The Hustler"
,"Rear Window"
,"The Rules of the Game"
,"One Flew Over the Cuckoo’s Nest"
,"A Man for All Seasons"
,"An American Werewolf in London"
,"The Tree of Wooden Clogs"
,"Touch of Evil"
,"Before Sunset"
,"Fitzcarraldo"
,"I Am Cuba"
,"Anchorman: The Legend of Ron Burgundy"
,"The Conversation"
,"Blazing Saddles"
,"Rio Bravo"
,"Miller’s Crossing"
,"Withnail and I"
,"The Wages of Fear"
,"The Battle of Algiers"
,"Los Olvidados"
,"The Princess Bride"
,"A Woman Under the Influence"
,"The Silence of the Lambs"
,"A Bout de souffle"
,"Pat Garrett and Billy the Kid"
,"The Sting"
,"Lost in Translation"
,"Harvey"
,"The Man Who Would Be King"
,"The Last of the Mohicans"
,"Pan’s Labyrinth"
,"Double Indemnity"
,"Seven"
,"Duck Soup"
,"Amadeus"
,"Dances with Wolves"
,"Cool Hand Luke"
,"Blow Out"
,"As Good as It Gets"
,"Snow White and the Seven Dwarfs"
,"Almost Famous"
,"Cyrano De Bergerac"
,"There Will Be Blood"
,"Sophie’s Choice"
,"Shampoo"
,"Notorious"
,"Z"
,"The Red Shoes"
,"The French Connection"
,"Gladiator"
,"Boogie Nights"
,"The Innocents"
,"Betty Blue"
,"Badlands"
,"Saving Private Ryan"
,"True Romance"
,"Unforgiven"
,"The Royal Tenenbaums"
,"Being There"
,"The Year of Living Dangerously"
,"A Nightmare on Elm Street"
,"The Bridge on the River Kwai"
,"The Searchers"
,"Partie de campagne"
,"Goldfinger"
,"Don’t Look Now"
,"Tootsie"
,"Viridiana"
,"La Haine"
,"Brief Encounter"
,"The Wizard of Oz"
,"Memento"
,"Superman the Movie"
,"Rushmore"
,"A Canterbury Tale"
,"City of God"
,"Hellzapoppin’"
,"Toy Story 2"
,"To Kill a Mockingbird"
,"Beyond the Valley of the Dolls"
,"Performance"
,"Le Samourai"
,"Dirty Harry"
,"Paths of Glory"
,"United 93"
,"The Big Country"
,"School of Rock"
,"Ghostbusters"
,"Big"
,"Brokeback Mountain"
,"Eraserhead"
,"Ed Wood"
,"Bicycle Thieves"
,"It’s a Wonderful Life"
,"Amélie"
,"Point Break"
,"Fargo"
,"The Texas Chain Saw Massacre"
,"Before Sunrise"
,"JFK"
,"The Killer"
,"Life of Brian"
,"The Bride of Frankenstein"
,"The Addiction"
,"The Exorcist"
,"The Misfits"
,"The Departed"
,"Local Hero"
,"Platoon"
,"Moulin Rouge!"
,"M"
,"Songs from the Second Floor"
,"Army of Shadows"
,"Jackie Brown"
,"Sunday Bloody Sunday"
,"The Magnificent Seven"
,"Mr. Hulot’s Holiday"
,"The Outlaw Josey Wales"
,"Far From Heaven"
,"McCabe & Mrs Miller"
,"Mother and Son"
,"Safe"
,"Distant Voices, Still Lives"
,"Get Carter"
,"Romeo + Juliet"
,"Léon"
,"No Country for Old Men"
,"Festen"
,"Howl’s Moving Castle"
,"Shaun of the Dead"
,"Jurassic Park"
,"Indiana Jones and the Temple of Doom"
,"The Bourne Ultimatum"
,"Battle Royale"
,"Black Narcissus"
,"Delicatessen"
,"Requiem for a Dream"
,"Cinema Paradiso"
,"Forrest Gump"
,"Brighton Rock"
,"King Kong"
,"Heimat ("
,"Dazed and Confused"
,"Downfall"
,"The Philadelphia Story"
,"All That Jazz"
,"Pandora’s Box"
,"My Darling Clementine"
,"Sunrise"
,"Darling"
,"The Leopard"
,"First Blood"
,"The Verdict"
,"Ninotchka"
,"Le Quai des brumes"
,"The Black Cat"
,"The Blues Brothers"
,"Groundhog Day"
,"Field of Dreams"
,"Roman Holiday"
,"The Virgin Suicides"
,"Das Boot"
,"American Graffiti"
,"A.I. Artificial Intelligence"
,"Ghost World"
,"Crimes and Misdemeanors"
,"The Lady Vanishes"
,"A Place in the Sun"
,"The Death of Mr. Lazarescu"
,"Pee-Wee’s Big Adventure"
,"The Bird with the Crystal Plumage"
,"The Maltese Falcon"
,"Sin City"
,"My Neighbour Totoro"
,"Layer Cake"
,"On the Town"
,"Carlito’s Way"
,"National Lampoon’s Animal House"
,"Mad Max 2"
,"Interview with the Vampire"
,"The Godfather Part III"
,"Ran"
,"Scarface"
,"Solaris"
,"L’avventura"
,"Secrets and Lies"
,"Who Framed Roger Rabbit"
,"John Carpenter’s The Thing"
,"Rashomon"
,"Rocco and His Brothers"
,"Le belle et la bête"
,"La maman et la putain"
,"The Red Balloon"
,"The Untouchables"
,"All the President’s Men"
,"It Happened One Night"
,"Le cercle rouge"
,"The Palm Beach Story"
,"Sawdust and Tinsel"
,"Love and Death"
,"The Best Years of Our Lives"
,"Together"
,"Radio Days"
,"The Prestige"
,"Indiana Jones and the Last Crusade"
,"Midnight Cowboy"
,"The Terminator"
,"Transformers"
,"Gremlins"
,"American History X"
,"Suspiria"
,"Battleship Potemkin"
,"Sweet Smell of Success"
,"Sense and Sensibility"
,"Trainspotting"
,"Midnight Run"
,"Rebecca"
,"The Lion King"
,"Braveheart"
,"Funny Face"
,"Aladdin"
,"The Last Seduction"
,"Lone Star"
,"Kill Bill Vol. 1"
,"Out of Sight"
,"The Nightmare Before Christmas"
,"The Truman Show"
,"The Lives of Others"
,"Star Wars Episode III: Revenge of the Sith"
,"The Green Mile"
,"The Sixth Sense"
,"Grease"
,"The Magnificent Ambersons"
,"The Seventh Seal"
,"Titanic"
,"300"
,"Jules et Jim"
,"Spirited Away"
,"High and Low"
,"The Passenger"
,"The Gold Rush"
,"Monsters, Inc."
,"The Last Waltz"
,"Fatal Attraction"
,"Leave Her to Heaven"
,"All About Eve"
,"Au hasard Balthazar"
,"Arthur"
,"Planet of the Apes"
,"Zulu"
,"Unfaithfully Yours"
,"Bugsy Malone"
,"Un chien andalou"
,"Sunshine"
,"Napoléon"
,"The Long Goodbye"
,"Russian Ark"
,"The Lady Eve"
,"The Return"
,"Clerks"
,"The Elephant Man"
,"Good Morning, Vietnam"
,"Natural Born Killers"
,"The Bourne Identity"
,"Predator"
,"Cabaret"
,"Airplane!"
,"The Breakfast Club"
,"Rocky"
,"Pirates of the Caribbean: The Curse of the Black Pearl"
,"Army of Darkness"
,"Wall-E"
,"Hot Fuzz"
,"Four Weddings and a Funeral"
,"Zodiac"
,"Mean Streets"
,"The Goonies"
,"Ratatouille"
,"Children of Men"
,"Monty Python and the Holy Grail"
,"Caché"
,"Serenity"
,"The Shop Around the Corner"
,"Ace in the Hole"
,"The Great Silence"
,"Rain Man"
,"The English Patient"
,"Election"
,"2 Days in Paris"
,"Mulholland Drive"
,"Paris, Texas"
,"Garden State"
,"Cloverfield"
,"Casino"
,"The Assassination of Jesse James by the Coward Robert Ford"
,"Night of the Living Dead"
,"Killer of Sheep"
,"Greed"
,"The Incredibles"
,"Batman Returns"
,"Little Miss Sunshine"
,"Do the Right Thing"
,"RoboCop"
,"Dirty Dancing"
,"Iron Man"
,"The Jungle Book"
,"Zelig"
,"Men in Black"
,"A Hard Day’s Night"
,"Spider-Man 2"
,"Heathers"
,"Finding Nemo"
,"The Double Life of Véronique"
,"Dawn of the Dead"
,"Bad Taste"
,"Lords of Dogtown"
,"V for Vendetta"
,"Days of Heaven"
,"Jerry Maguire"
,"Lethal Weapon"
,"A Man Escaped"
,"Kill Bill Vol. 2"
,"To Have and Have Not"
,"Wonder Boys"
,"Enduring Love"
,"Spring in a Small Town"
,"The Enigma of Kaspar Hauser"
,"Danger: Diabolik"
,"Big Trouble in Little China"
,"Electra Glide in Blue"
,"X-Men 2"
,"Good Will Hunting"
,"The Cat Concerto"
,"American Psycho"
,"Beauty and the Beast"
,"Spider-Man"
,"The Lost Boys"
,"Grosse Pointe Blank"
,"Akira"
,"Being John Malkovich"
,"Atonement"
,"Dog Day Afternoon"
,"Hairspray"
,"Dumb and Dumber"
,"High Fidelity"
,"Ten"
,"A History of Violence"
,"Star Wars Episode I: The Phantom Menace"
,"King Kong"
,"Speed"
,"Unbreakable"
,"Indiana Jones and the Kingdom of the Crystal Skull"
,"The Bourne Supremacy"
,"Top Gun"
,"28 Days Later"
,"Full Metal Jacket"
,"Batman"
,"Ikiru"
,"Crash"
,"Halloween"
,"Dead Man’s Shoes"
,"Juno"
,"Seven Brides for Seven Brothers"
,"12 Monkeys"
,"Snatch"
,"The Deer Hunter"
,"The Crow"
,"Fear and Loathing in Las Vegas"
,"Glengarry Glen Ross"
,"Harry Potter and the Prisoner of Azkaban"
,"Le Doulos"
,"Into the Wild"
,"Enter the Dragon"
,"Pirates of the Caribbean: Dead Man’s Chest"
,"Santa Sangre"
,"Rebel Without a Cause"
,"Flesh"
,"The Secret Life of Walter Mitty"
,"The Son’s Room"
,"Topsy-Turvy"
,"Scream"
,"The Big Red One"
,"The Fountain"
,"The Wicker Man"
,"Breakfast at Tiffany’s"
,"Superbad"
,"Princess Mononoke"
,"Brick"
,"Sweeney Todd: The Demon Barber of Fleet Street"
,"Ben-Hur"
,"Amores Perros"
,"In the Company of Men"
,"Sideways"
,"Jailhouse Rock"
,"Superman Returns"
,"Crouching Tiger, Hidden Dragon"
,"Back to the Future Part II"
,"Saw"
,"Ocean’s Eleven"
]